import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      // Regenerated by `next build`/`next dev` on every run and gitignored;
      // its triple-slash references are Next's own convention, not ours.
      'next-env.d.ts',
      'public/sw.js',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'src/generated/**',
      // Local layout-audit harness; never committed.
      '.audit/**',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Zero `any` is a hard requirement (§0.5).
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // Forbidden packages (§4).
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: 'axios', message: 'Use the native fetch API (§4).' },
            { name: 'moment', message: 'Use date-fns (§4).' },
            { name: 'bcrypt', message: 'Use @node-rs/argon2 (§4).' },
            { name: 'bcryptjs', message: 'Use @node-rs/argon2 (§4).' },
            { name: 'styled-components', message: 'Use Tailwind + design tokens (§4).' },
          ],
          patterns: [
            { group: ['@vercel/*'], message: 'Vercel-only packages break Hostinger deployment (§2 C1).' },
            {
              group: ['@mui/*', '@chakra-ui/*', 'antd'],
              message: 'No opinionated UI kits — use components/ui (§4).',
            },
          ],
        },
      ],
    },
  },
  {
    // Prisma is server-only. UI components never import it (§5).
    files: ['src/components/**/*.{ts,tsx}', 'src/app/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: '@prisma/client', message: 'UI never imports Prisma — go through server/services (§5).' },
            { name: 'axios', message: 'Use the native fetch API (§4).' },
          ],
          patterns: [
            { group: ['@/server/db', '@/server/db/*'], message: 'UI never imports the Prisma client directly (§5).' },
            { group: ['@vercel/*'], message: 'Vercel-only packages break Hostinger deployment (§2 C1).' },
          ],
        },
      ],
    },
  },
  {
    files: ['scripts/**/*.ts', 'prisma/**/*.ts', 'tests/**/*.ts', 'tests/**/*.tsx'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // A form must say how it submits.
    //
    // Every client form here handles `onSubmit` and calls a Server Action from
    // JavaScript. Before hydration there is no handler, and a form with no
    // `method` falls back to the HTML default — GET — serialising every field
    // into the URL. Found by accident on the login page:
    //   /fr/connexion?email=admin%40cfi.ma&password=Cfi%21SuperAdmin2026
    // On a slow phone a real person tapping « Se connecter » early does the
    // same, and the password lands in browser history, the host's access logs
    // and the Referer of the next request. Same for the reset and register
    // forms, the admin bank details, and the certificate code whose own page
    // promises it never reaches a URL.
    //
    // `method="post"` makes a premature submit a POST to the page, which
    // simply renders it again. A form with `action={serverAction}` is already
    // a POST (React forbids setting `method` on it), so either attribute
    // satisfies the rule — and a deliberate GET, like a search box, just says
    // `method="get"`.
    files: ['src/**/*.tsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "JSXOpeningElement[name.name='form']:not(:has(JSXAttribute[name.name=/^(method|action)$/]))",
          message:
            'Give every <form> a `method` (or a Server Action `action`). Without one, a submit before hydration is a native GET that puts every field — passwords included — in the URL.',
        },
      ],
    },
  },
];

export default config;
