/* @jsxRuntime automatic @jsxImportSource react */
/**
 * Email #9 (§18) — « Accès activé — bonne formation ! ».
 *
 * The good news. One CTA into the course; the invoice is linked rather than
 * attached (it is generated by the `GENERATE_INVOICE` job moments after the
 * approval commits, and lives behind the authenticated file gateway — a link
 * stays valid, an attachment would have to wait for the job).
 */

import type { ReactNode } from 'react';
import { z } from 'zod';
import {
  EmailCta,
  EmailDetails,
  EmailHeading,
  EmailLayout,
  EmailLink,
  EmailParagraph,
  Ltr,
  firstNameOf,
  textBody,
  type EmailContext,
  type EmailTemplate,
} from './layout';
import type { Locale } from '@/i18n/routing';

export const requestApprovedPropsSchema = z
  .object({
    fullName: z.string().min(1).max(120),
    courseTitle: z.string().min(1).max(200),
    reference: z.string().min(1).max(32),
    /** Pre-formatted amount, e.g. `1 200 DH`. */
    amountLabel: z.string().min(1).max(40),
    /** Absolute URL of the course — where « Commencer » lands. */
    courseUrl: z.string().url(),
    /** Absolute URL of `/[locale]/espace/demandes`, where the invoice download lives. */
    requestsUrl: z.string().url(),
  })
  .strict();

export type RequestApprovedProps = z.infer<typeof requestApprovedPropsSchema>;

interface Copy {
  readonly subject: string;
  readonly preview: string;
  readonly heading: string;
  readonly greeting: (firstName: string) => string;
  readonly intro: (courseTitle: string) => string;
  readonly referenceLabel: string;
  readonly amountLabel: string;
  readonly courseLabel: string;
  readonly cta: string;
  readonly invoiceLead: string;
  readonly invoiceLink: string;
}

const COPY: Record<Locale, Copy> = {
  fr: {
    subject: 'Accès activé — bonne formation !',
    preview: 'Votre paiement est confirmé, votre formation vous attend.',
    heading: 'Votre accès est activé',
    greeting: (firstName) => `Bonjour ${firstName},`,
    intro: (courseTitle) =>
      `Votre paiement a été confirmé et votre accès à la formation « ${courseTitle} » est maintenant actif. Bonne formation !`,
    referenceLabel: 'Référence',
    amountLabel: 'Montant réglé',
    courseLabel: 'Formation',
    cta: 'Commencer la formation',
    invoiceLead: 'Votre facture est disponible dans votre espace :',
    invoiceLink: 'Télécharger ma facture',
  },
  ar: {
    subject: 'تم تفعيل الولوج — تكوينًا موفقًا!',
    preview: 'تم تأكيد أدائكم، ودورتكم التدريبية في انتظاركم.',
    heading: 'تم تفعيل ولوجكم',
    greeting: (firstName) => `مرحبًا ${firstName}،`,
    intro: (courseTitle) =>
      `تم تأكيد أدائكم وأصبح ولوجكم إلى الدورة التدريبية «${courseTitle}» مفعّلًا الآن. تكوينًا موفقًا!`,
    referenceLabel: 'المرجع',
    amountLabel: 'المبلغ المؤدى',
    courseLabel: 'الدورة التدريبية',
    cta: 'بدء الدورة',
    invoiceLead: 'فاتورتكم متوفرة في فضائكم:',
    invoiceLink: 'تحميل فاتورتي',
  },
  en: {
    subject: 'Access activated — enjoy your course!',
    preview: 'Your payment is confirmed; your course is waiting.',
    heading: 'Your access is activated',
    greeting: (firstName) => `Hello ${firstName},`,
    intro: (courseTitle) =>
      `Your payment has been confirmed and your access to the course “${courseTitle}” is now active. Enjoy your training!`,
    referenceLabel: 'Reference',
    amountLabel: 'Amount paid',
    courseLabel: 'Course',
    cta: 'Start the course',
    invoiceLead: 'Your invoice is available in your space:',
    invoiceLink: 'Download my invoice',
  },
  es: {
    subject: 'Acceso activado — ¡buena formación!',
    preview: 'Su pago está confirmado; su formación le espera.',
    heading: 'Su acceso está activado',
    greeting: (firstName) => `Hola ${firstName}:`,
    intro: (courseTitle) =>
      `Su pago ha sido confirmado y su acceso a la formación «${courseTitle}» ya está activo. ¡Buena formación!`,
    referenceLabel: 'Referencia',
    amountLabel: 'Importe pagado',
    courseLabel: 'Formación',
    cta: 'Empezar la formación',
    invoiceLead: 'Su factura está disponible en su espacio:',
    invoiceLink: 'Descargar mi factura',
  },
};

function body(props: RequestApprovedProps, ctx: EmailContext): ReactNode {
  const copy = COPY[ctx.locale];
  return (
    <EmailLayout ctx={ctx} preview={copy.preview}>
      <EmailHeading ctx={ctx}>{copy.heading}</EmailHeading>
      <EmailParagraph ctx={ctx}>{copy.greeting(firstNameOf(props.fullName))}</EmailParagraph>
      <EmailParagraph ctx={ctx}>{copy.intro(props.courseTitle)}</EmailParagraph>
      <EmailDetails
        ctx={ctx}
        rows={[
          { label: copy.courseLabel, value: props.courseTitle },
          { label: copy.amountLabel, value: <Ltr>{props.amountLabel}</Ltr> },
          {
            label: copy.referenceLabel,
            value: (
              <Ltr>
                <span style={{ fontFamily: 'ui-monospace, Menlo, Consolas, monospace' }}>
                  {props.reference}
                </span>
              </Ltr>
            ),
          },
        ]}
      />
      <EmailCta ctx={ctx} href={props.courseUrl} label={copy.cta} />
      <EmailParagraph ctx={ctx} muted>
        {copy.invoiceLead} <EmailLink href={props.requestsUrl}>{copy.invoiceLink}</EmailLink>
      </EmailParagraph>
    </EmailLayout>
  );
}

function text(props: RequestApprovedProps, ctx: EmailContext): string {
  const copy = COPY[ctx.locale];
  return textBody(ctx, [
    copy.heading,
    copy.greeting(firstNameOf(props.fullName)),
    copy.intro(props.courseTitle),
    `${copy.courseLabel} : ${props.courseTitle}\n${copy.amountLabel} : ${props.amountLabel}\n${copy.referenceLabel} : ${props.reference}`,
    `${copy.cta} :\n${props.courseUrl}`,
    `${copy.invoiceLead}\n${copy.invoiceLink} : ${props.requestsUrl}`,
  ]);
}

export const requestApprovedTemplate: EmailTemplate<RequestApprovedProps> = {
  id: 'request-approved',
  schema: requestApprovedPropsSchema,
  subject: (_props, ctx) => COPY[ctx.locale].subject,
  body,
  text,
};
