/**
 * `npm run covers` — produce the seeded courses' and parcours' cover photos.
 *
 *   npm run covers                   download, crop and write every cover
 *   npm run covers -- --only <slug>  one cover
 *
 * Each cover is a photograph chosen for its course (`scripts/covers/manifest.ts`
 * records which one, by whom, and where it was published), fetched from the
 * provider's image CDN, cropped to the card's 16 / 9 at 1600 × 900 and written
 * as a progressive JPEG under `public/brand/seed/`, where the seed's cover keys
 * point (`seed/courses/<slug>.jpg`, `seed/paths/<slug>.jpg`). The output is
 * committed; this script only has to run again when a cover changes.
 *
 * It also rewrites `public/brand/seed/CREDITS.md` from the manifest, so the
 * attribution can never drift from the files.
 *
 * Licences: every source is published under the Unsplash License or the Pexels
 * License — free for commercial use, no permission needed, attribution
 * appreciated rather than required. We credit anyway.
 */

import { mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import process from 'node:process';

import sharp from 'sharp';

import { COVERS, coverKey, type CoverEntry } from './covers/manifest';

const WIDTH = 1600;
const HEIGHT = 900;
/** `public/brand/README.md`: committed seed images stay under 500 KB. */
const MAX_BYTES = 500 * 1024;

function sourceUrl(entry: CoverEntry): string {
  const { source } = entry;
  // Ask the CDN for a generous width and crop locally, so the crop position is
  // ours (and reviewable) rather than the CDN's guess.
  return source.provider === 'unsplash'
    ? `https://images.unsplash.com/${source.id}?w=2400&fm=jpg&q=90`
    : `https://images.pexels.com/photos/${source.id}/${source.file}?auto=compress&cs=tinysrgb&w=2400`;
}

async function download(url: string): Promise<Buffer> {
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    const response = await fetch(url, { headers: { 'user-agent': 'cfi-covers/1.0' } });
    if (response.ok) return Buffer.from(await response.arrayBuffer());
    if (attempt === 3) throw new Error(`${url} → HTTP ${response.status}`);
    await new Promise((resolve) => setTimeout(resolve, 1000 * attempt));
  }
  throw new Error('unreachable');
}

async function writeCover(entry: CoverEntry): Promise<void> {
  const out = join('public', 'brand', coverKey(entry));
  mkdirSync(dirname(out), { recursive: true });

  const original = await download(sourceUrl(entry));
  let image = sharp(original).rotate();
  if (entry.region !== undefined) {
    const { width = 0, height = 0 } = await sharp(original).rotate().metadata();
    image = sharp(
      await image
        .extract({
          left: Math.round(entry.region.left * width),
          top: Math.round(entry.region.top * height),
          width: Math.round(entry.region.width * width),
          height: Math.round(entry.region.height * height),
        })
        .toBuffer(),
    );
  }
  const cropped = image.resize(WIDTH, HEIGHT, { fit: 'cover', position: entry.position });

  // Highest quality that fits the budget.
  for (const quality of [82, 78, 74, 70]) {
    await cropped
      .clone()
      .jpeg({ quality, mozjpeg: true, progressive: true })
      .toFile(out);
    const bytes = statSync(out).size;
    if (bytes <= MAX_BYTES) {
      console.log(`  ${out}  ${Math.round(bytes / 1024)} KB  q${quality}`);
      return;
    }
  }
  throw new Error(`${out} stays over 500 KB even at q70`);
}

function writeCredits(): void {
  const rows = COVERS.map((entry) => {
    const { source } = entry;
    const provider = source.provider === 'unsplash' ? 'Unsplash' : 'Pexels';
    return `| \`${coverKey(entry)}\` | [${source.photographer}](${source.photographerUrl}) | [${provider}](${source.pageUrl}) |`;
  });
  const body = `# Course cover photographs

Generated by \`npm run covers\` from \`scripts/covers/manifest.ts\` — edit the manifest, not
this file.

Every photograph is published under the [Unsplash License](https://unsplash.com/license) or
the [Pexels License](https://www.pexels.com/license/): free for commercial use, no permission
needed. Attribution is not required by either licence; we give it anyway.

| File | Photographer | Source |
|---|---|---|
${rows.join('\n')}
`;
  writeFileSync(join('public', 'brand', 'seed', 'CREDITS.md'), body);
  console.log('  public/brand/seed/CREDITS.md');
}

async function main(): Promise<void> {
  const i = process.argv.indexOf('--only');
  const only = i === -1 ? null : (process.argv[i + 1] ?? null);
  const entries = only === null ? COVERS : COVERS.filter((entry) => entry.slug === only);
  if (entries.length === 0) throw new Error(`No cover named ${only} in scripts/covers/manifest.ts`);

  for (const entry of entries) await writeCover(entry);
  writeCredits();
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
